export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT"
export const CREATE_LESSON_PLAN = "CREATE_LESSON_PLAN";
export const FETCH_LESSON_PLAN = "FETCH_LESSON_PLAN";
export const FETCH_LESSON_PLANS = "FETCH_LESSON_PLANS";
export const EDIT_LESSON_PLAN = "EDIT_LESSON_PLAN";
export const DELETE_LESSON_PLAN = "DELETE_LESSON_PLAN";
